[package]
name = "maivin-websrv"
description = "Maivin Web UI Server"
repository = "https://bitbucket.org/au-zone/maivin-websrv"
license = "CLOSED"
version = "0.0.0"
edition = "2021"

[profile.release]
opt-level = 3
lto = true
strip = true
debug = false

[profile.profiling]
inherits = "release"
strip = false
debug = true

[dependencies]
async-std = {version = "1.12", features = ["attributes"] }
cdr = "0.2.4"
clap = { version = "4.5.27", features = ["derive", "env"] }
tokio = { version = "1.43.0", features = ["full"] }
serde = "1.0.217"
serde_json = "1.0.138"
zenoh = "0.10.0-rc"
edgefirst-schemas = "1.2.4"
futures = "0.3.31"
image = { version = "0.24.7", default-features = false, features = ["jpeg_rayon", "png"] }
async-scoped = {version = "0.9.0", features = ["use-async-std"] }
fast_image_resize = "5.1.1"
log = "0.4.25"
actix-web = { version = "4.0", features = ["openssl"] }
actix-files = "0.6"
actix-web-actors = "4.3.0"
actix = "0.13"
openssl = { version = "0.10.69", features = ["vendored"] }
tokio-stream = { version = "0.1.17", features = ["full"] }
futures-util = "0.3.31"
local-ip-address = "0.6.3"
env_logger = "0.11.6"
mcap = "0.14.1"
anyhow = "1.0.95"
camino = "1.1.9"
memmap = "0.7.0"
chrono = "0.4.29"
maivin-publisher = { git = "ssh://git@bitbucket.org/au-zone/maivin-publisher.git", rev = "5defd71a" }
uuid = { version = "1.12.1", features = ["v1"] }
pnet = "0.35.0"
regex = "1"
hostname = "0.4.0"
percent-encoding = "2"
actix-web-lab = "0.23.0"
fs2 = "0.4.3"
mime = "0.3.17"
async-stream = "0.3.6"
