[package]
name = "maivin-websrv"
description = "Maivin Web UI Server"
repository = "https://bitbucket.org/au-zone/maivin-websrv"
license = "CLOSED"
version = "0.0.0"
edition = "2021"

[profile.release]
opt-level = 3
lto = true
strip = true
debug = false

[profile.profiling]
inherits = "release"
strip = false
debug = true

[dependencies]
actix = "0.13"
actix-files = "0.6"
actix-web = { version = "4.0", features = ["openssl"] }
actix-web-actors = "4.3.0"
actix-web-lab = "0.23.0"
anyhow = "1.0.95"
async-stream = "0.3.6"
camino = "1.1.9"
cdr = "0.2.4"
chrono = "0.4.29"
clap = { version = "4.5.28", features = ["derive", "env"] }
env_logger = "0.11.6"
fs2 = "0.4.3"
hostname = "0.4.0"
log = "0.4.25"
maivin-publisher = { git = "ssh://git@bitbucket.org/au-zone/maivin-publisher.git", rev = "5defd71a" }
mcap = "0.15.0"
memmap = "0.7.0"
mime = "0.3.17"
openssl = { version = "0.10.70", features = ["vendored"] }
percent-encoding = "2"
pnet = "0.35.0"
regex = "1"
serde = "1.0.217"
serde_json = "1.0.138"
tokio = { version = "1.43.0", features = ["rt-multi-thread", "time", "io-std"] }
uuid = { version = "1.13.1", features = ["v1"] }
zenoh = "1.2.1"
