[package]
name = "maivin-websrv"
description = "Maivin Web UI Server"
repository = "https://bitbucket.org/au-zone/maivin-websrv"
license = "CLOSED"
version = "0.0.0"
edition = "2021"

[profile.release]
opt-level = 3
lto = true
strip = true
debug = false

[profile.profiling]
inherits = "release"
strip = false
debug = true

[dependencies]
async-std = {version = "1.12", features = ["attributes"] }
cdr = "0.2"
clap = { version = "4.4", features = ["derive", "env"] }
tokio = { version = "1", features = ["full"] }
serde = "1.0"
serde_json = "1.0"
zenoh = "0.10.0-rc"
edgefirst-schemas = "1.2.4"
futures = "0.3.29"
image = { version = "0.24.7", default-features = false, features = ["jpeg_rayon", "png"] }
async-scoped = {version = "0.8.0", features = ["use-async-std"] }
fast_image_resize = "2.7.3"
log = "0.4.20"
actix-web = { version = "4.0", features = ["openssl"] }
actix-files = "0.6"
actix-web-actors = "4.0"
actix = "0.13"
openssl = { version = "0.10", features = ["vendored"] }
tokio-stream = { version = "0.1", features = ["full"] }
futures-util = "0.3"
local-ip-address = "0.6.1"
env_logger = "0.10"
mcap = "0.9.0"
anyhow = "1.0"
camino = "1.1.6"
memmap = "0.7.0"
chrono = "0.4"
maivin-publisher = { git = "ssh://git@bitbucket.org/au-zone/maivin-publisher.git" }
uuid = { version = "1.3", features = ["v1"] }
pnet = "0.30.0"
regex = "1"
hostname = "0.3.1"